# https://www.exclamationlabs.com/blog/continuous-deployment-to-npm-using-gitlab-ci/
image: node:latest

stages:
  - test
  - deploy

# CACHING 
before_script:
  - npm install

cache:
  paths:
    - node_modules/

# TESTS
test:node:latest:
  stage: test
  script:
    - npm test

test:lint:
  stage: test
  script:
    - npm run lint

# PUBLISH TO NPM
publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
