# https://www.exclamationlabs.com/blog/continuous-deployment-to-npm-using-gitlab-ci/
image: node:latest

before_script:
  - npm install

cache:
  paths:
    - node_modules/

test:node:latest:
   script:
    - npm test

test:lint:
  script:
    - npm run lint

publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
