# https://www.exclamationlabs.com/blog/continuous-deployment-to-npm-using-gitlab-ci/
image: node:latest

before_script:  
  - npm install

cache:  
  paths:
    - node_modules/

test:
   script:
    - npm test

publish:  
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish